# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: default
    main: .
    binary: docker-machine-driver-hetzner

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: CosmoAbdon
    name: docker-machine-driver-hetzner

  draft: false
  prerelease: auto

  name_template: "{{.ProjectName}} v{{.Version}}"

  extra_files:
    - glob: ./dist/checksums.txt

brews:
  - repository:
      owner: CosmoAbdon
      name: homebrew-tap

    homepage: "https://github.com/CosmoAbdon/docker-machine-driver-hetzner"
    description: "Docker Machine driver for Hetzner Cloud"

    install: |
      bin.install "docker-machine-driver-hetzner"

dockers:
  - image_templates:
      - "zeveery/docker-machine-driver-hetzner:{{ .Version }}"
      - "zeveery/docker-machine-driver-hetzner:latest"

    dockerfile: Dockerfile

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
