# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: default
    main: .
    binary: docker-machine-driver-hetzner

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: CosmoAbdon
    name: docker-machine-driver-hetzner

  draft: false
  prerelease: auto

  name_template: "{{.ProjectName}} v{{.Version}}"

  extra_files:
    - glob: ./dist/checksums.txt
